apiVersion: apps/v1
kind: Deployment
metadata:
  name: longcovid
spec:
  selector:
    matchLabels:
      app: longcovid
  template:
    metadata:
      labels:
        app: longcovid
    spec:
      containers:
      - name: longcovid
        image: IMAGE_URL/longcovid:latest
        ports:
        - containerPort: 80
        resources:
            limits:
              cpu: "250m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: long-covid-service-svc
spec:
  type: LoadBalancer
  selector:
    app: longcovid
  ports:
  - port: 80